export const BANDS = [60, 170, 310, 600, 1000, 3000, 6000, 12000, 14000, 16000];

export const WINDOWS = {
  MAIN: "MAIN",
  PLAYLIST: "PLAYLIST",
  EQUALIZER: "EQUALIZER"
};

export const LOAD_STYLE = {
  BUFFER: "BUFFER",
  PLAY: "PLAY"
};

export const MEDIA_TAG_REQUEST_STATUS = {
  INITIALIZED: "INITIALIZED",
  FAILED: "FAILED",
  COMPLETE: "COMPLETE",
  NOT_REQUESTED: "NOT_REQUESTED"
};

export const UTF8_ELLIPSIS = "\u2026";
export const CHARACTER_WIDTH = 5;
export const PLAYLIST_RESIZE_SEGMENT_WIDTH = 25;
export const PLAYLIST_RESIZE_SEGMENT_HEIGHT = 29;
export const MIN_PLAYLIST_WINDOW_WIDTH = 275;
export const TRACK_HEIGHT = 13;
export const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
