name: Compressed Size

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        build-script: "deploy"
        pattern: "./packages/webamp/built/*bundle.min.js"